### ISSUE TITLE
Update Schedule Section

### ISSUE THREAD

**Issue by meredyth811** [ourlittlewedding/ourlittlewedding.github.io#3]
Friday, October 20
Welcome Gathering
Location: TBD
8:30pm

Saturday, October 21
The Wedding!
The Lenox Library
4:00pm 
Followed by cocktail hour, dinner, and dancing!

Sunday, October 22
Send Off Brunch
Location: Pederson House at 12 Sunset Ave
Drop in anytime between 9:30am and noon

**Comment by maptastik** [comment]
@meredyth811 Are all these times confirmed? I've heard some discussion that not all of these are set.

**Comment by meredyth811** [comment]
No.

**Comment by meredyth811** [comment]
Actually let's keep 8:30pm for the welcome event. We'll move the rehearsal things earlier if we need to make more time for the rehearsal dinner. So times are confirmed (for now...)

**Comment by meredyth811** [comment]
Do we want to move the brunch to 10am? Now that we know we are mini-mooning in CT, we probably won't need to head out until closer to 1?

**Comment by maptastik** [comment]
I agree.
